tabela = ("Botafogo", "Flamengo", "Bahia", "Athletico-PR", "Palmeiras", "São Paulo", "Bragantino", "Cruzeiro", "Atlético-MG", "Internacional", "Juventude", "Fortaleza", "Atlético-GO", "Cuiabá", "Vasco da Gama", "Corinthians", "Grêmio", "Criciúma", "Fluminense", "EC Vitória")
print(f'Os 5 primeiros colocados da tabela atual são {tabela[0:5]}.')
print(' ')
print(f'Os 4 ultimos da tabela são {tabela[-4:]}.')
print(' ')
print(f'A ordem alfabética dos time seria {sorted(tabela,)}.')
print(' ')
print(f'O time da Chapecoense ta na série B JUNTO COM O PEIXAOKKKKKKKKKKK')
print(f'Mas o time do São Paulo está em {tabela.index('São Paulo')} lugar.')
